/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormRadioGroup: typeof import('bootstrap-vue-next')['BFormRadioGroup']
    BPopover: typeof import('bootstrap-vue-next')['BPopover']
    IBiBookmarkPlus: typeof import('~icons/bi/bookmark-plus')['default']
    IBiDownload: typeof import('~icons/bi/download')['default']
    IBiExclamationDiamond: typeof import('~icons/bi/exclamation-diamond')['default']
    IBiInfoSquare: typeof import('~icons/bi/info-square')['default']
    IBiJournalAlbum: typeof import('~icons/bi/journal-album')['default']
    IFaFolder: typeof import('~icons/fa/folder')['default']
    IFaFolderOpen: typeof import('~icons/fa/folder-open')['default']
    IFaSearch: typeof import('~icons/fa/search')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TreeItem: typeof import('./src/components/tree-view/TreeItem.vue')['default']
    TreeView: typeof import('./src/components/tree-view/TreeView.vue')['default']
  }
}
